
version: '2'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  odoo:
    image: odoo
    container_name: odoo
    ports:
      - "8069:8069"
    links:
      - db:db
    depends_on:
      - db
    tty: true
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo
